// patentPdf.ts — 특허 원문 PDF(데모 표지) 생성·다운로드.
// 외부 라이브러리 없이 최소 PDF를 직접 구성한다. (base14 Helvetica = ASCII 위주)
import type { PatentResult } from '../types';

// 비ASCII 문자는 PDF base14 폰트로 렌더되지 않으므로 안전하게 치환
function ascii(s: string): string {
  return (s || '').replace(/[()\\]/g, ' ').replace(/[^\x20-\x7E]/g, '?');
}

function buildPdf(lines: string[]): Blob {
  const esc = (t: string) => t.replace(/[()\\]/g, m => '\\' + m);
  // 본문 content stream: 한 줄씩 아래로
  let body = 'BT /F1 11 Tf 50 790 Td 14 TL\n';
  lines.forEach((ln, i) => {
    body += i === 0 ? `(${esc(ln)}) Tj\n` : `T* (${esc(ln)}) Tj\n`;
  });
  body += 'ET';

  const objs: string[] = [];
  objs.push('<</Type/Catalog/Pages 2 0 R>>');
  objs.push('<</Type/Pages/Kids[3 0 R]/Count 1>>');
  objs.push('<</Type/Page/Parent 2 0 R/MediaBox[0 0 595 842]/Resources<</Font<</F1 5 0 R>>>>/Contents 4 0 R>>');
  objs.push(`<</Length ${body.length}>>\nstream\n${body}\nendstream`);
  objs.push('<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>');

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];
  objs.forEach((o, i) => {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${o}\nendobj\n`;
  });
  const xrefPos = pdf.length;
  pdf += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n`;
  offsets.forEach(off => { pdf += `${String(off).padStart(10, '0')} 00000 n \n`; });
  pdf += `trailer\n<</Size ${objs.length + 1}/Root 1 0 R>>\nstartxref\n${xrefPos}\n%%EOF`;

  return new Blob([pdf], { type: 'application/pdf' });
}

/** 특허 원문 PDF(데모 표지) 다운로드 */
export function downloadPatentPdf(d: PatentResult): void {
  const lines = [
    'PATENT DOCUMENT (DEMO COVER PAGE)',
    '',
    `Document No.   : ${ascii(d.number)}`,
    `Country / Kind : ${ascii(d.country)} / ${ascii(d.status)}`,
    `Title          : ${ascii(d.title)}`,
    `Applicant      : ${ascii(d.applicant)}  [${ascii(d.applicantCode || '-')}]`,
    `Inventors      : ${ascii(d.inventors)}`,
    `Application No.: ${ascii(d.applicationNo)}   (${ascii(d.applicationDate)})`,
    `Publication    : ${ascii(d.publicationNo)}   (${ascii(d.publicationDate)})`,
    `Registration   : ${ascii(d.registerNo)}   (${ascii(d.registerDate)})`,
    `IPC / CPC      : ${ascii(d.ipc)} / ${ascii(d.cpc)}`,
    `Agent          : ${ascii(d.agent || '-')}`,
    '',
    'Abstract:',
    ...wrap(ascii(d.abstract), 78),
    '',
    'Representative Claim:',
    ...wrap(ascii(d.repClaim), 78),
    '',
    '* This is a demo cover page generated by AXP. Non-ASCII (Korean/JP/CN)',
    '  text is shown as "?" due to base font limitations.',
  ];
  const blob = buildPdf(lines);
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `${d.number.replace(/[^\w.-]+/g, '_')}.pdf`;
  a.click();
  URL.revokeObjectURL(a.href);
}

function wrap(text: string, width: number): string[] {
  const words = (text || '').split(/\s+/);
  const out: string[] = [];
  let line = '';
  for (const w of words) {
    if ((line + ' ' + w).trim().length > width) { if (line) out.push(line); line = w; }
    else line = (line ? line + ' ' : '') + w;
  }
  if (line) out.push(line);
  return out.length ? out : [''];
}
