// 기능명세 항목 카탈로그 — docs/기능정의서.md 「메뉴·화면별 기능명세」의 구성요소별 통합표와 1:1.
// 목업 요소의 data-spec="<ID>"와 매칭되어 "명세 모드"에서 조회된다.
// 전 화면: PAT-INP / PAT-LST / PAT-DET / PAP-INP / PAP-LST / COM / SPC-*(명세서 작성). data-spec 부착과 1:1로 유지한다.

export interface SpecEntry {
  id: string;
  screen: string;
  component: string;
  display: string;        // 표시 정보·구성
  interaction: string;    // 기능·상호작용
  precondition: string;   // 사전조건
  postcondition: string;  // 사후결과
}

export const SPEC_CATALOG: Record<string, SpecEntry> = {
  'PAT-INP-010': {
    id: 'PAT-INP-010',
    screen: '특허 · 검색어 입력',
    component: '메타필터 (영역)',
    display: '국가 · 문헌종류 · 기간 · 상태 필터 묶음. 활성 칩=체크(✓)+색상',
    interaction: '↓ 필터별 (국가/문헌종류/기간/상태)',
    precondition: '화면 진입',
    postcondition: '개별 필터(PAT-INP-011~014) 참조',
  },
  'PAT-INP-011': {
    id: 'PAT-INP-011',
    screen: '특허 · 검색어 입력',
    component: '국가 필터',
    display: '전체 / KR / US / JP / CN / EP / PCT / DE / GB + "국가설정"으로 추가국가',
    interaction: '칩 토글("전체"=라디오, 해제 불가) · 국가설정 팝업에서 추가',
    precondition: '화면 진입',
    postcondition: '다음 검색 payload에 countries[] 포함',
  },
  'PAT-INP-012': {
    id: 'PAT-INP-012',
    screen: '특허 · 검색어 입력',
    component: '문헌종류 필터',
    display: '전체 / 공개 / 등록 / 실용공개 / 실용등록',
    interaction: '칩 토글("전체"=라디오)',
    precondition: '화면 진입',
    postcondition: '다음 검색 payload에 docTypes[] 포함',
  },
  'PAT-INP-013': {
    id: 'PAT-INP-013',
    screen: '특허 · 검색어 입력',
    component: '기간 필터',
    display: '전체 / 최근5·10·20년 + 일자범위(시작~종료 date)',
    interaction: '프리셋 라디오 선택 또는 일자 직접 입력',
    precondition: '화면 진입',
    postcondition: '다음 검색 payload에 dateFrom/dateTo 반영',
  },
  'PAT-INP-014': {
    id: 'PAT-INP-014',
    screen: '특허 · 검색어 입력',
    component: '상태 필터',
    display: '전체 / A(출원·심사중·등록) / I(거절·소멸·취하·포기·무효)',
    interaction: '칩 토글("전체"=전체 초기화, 빈 선택 방지)',
    precondition: '화면 진입',
    postcondition: '다음 검색 payload에 statuses[] 포함',
  },
  'PAT-INP-020': {
    id: 'PAT-INP-020',
    screen: '특허 · 검색어 입력',
    component: '검색어 범위 탭',
    display: 'KEY(명칭+요약+독립항) / TAC(명칭+요약+전체청구항) / DSC(명칭+요약+전체청구항+상세설명)',
    interaction: '탭 전환(라벨 정합은 명세 비교 확인 대상)',
    precondition: '화면 진입',
    postcondition: '선두 자유어에 적용될 범위코드 변경(직접 필드식은 불변)',
  },
  'PAT-INP-030': {
    id: 'PAT-INP-030',
    screen: '특허 · 검색어 입력',
    component: '입력방식 토글',
    display: '일반(textarea) / 편집기(구문강조+실시간 진단)',
    interaction: '모드 전환',
    precondition: '화면 진입',
    postcondition: '표시 방식 전환 · 편집기모드는 진단 표시(실행 차단 안 함)',
  },
  'PAT-INP-040': {
    id: 'PAT-INP-040',
    screen: '특허 · 검색어 입력',
    component: '검색식 입력창 + 검색/초기화 (영역)',
    display: '입력창 + 우측 검색·초기화 버튼',
    interaction: '↓ 액션별 (검색 실행 / 초기화)',
    precondition: '—',
    postcondition: '개별 액션(PAT-INP-041/042) 참조',
  },
  'PAT-INP-041': {
    id: 'PAT-INP-041',
    screen: '특허 · 검색어 입력',
    component: '검색 실행',
    display: '검색 버튼',
    interaction: '클릭 / ⏎',
    precondition: '검색식 입력창 또는 항목별 필드에 값 1개 이상',
    postcondition: 'searchQuery 조립·POST → 결과 목록 전환 · 히스토리 1건 추가 · (연동 시)URL 직렬화',
  },
  'PAT-INP-042': {
    id: 'PAT-INP-042',
    screen: '특허 · 검색어 입력',
    component: '초기화',
    display: '초기화 버튼',
    interaction: '클릭',
    precondition: '—',
    postcondition: '입력값·활성필드를 디폴트로 복원',
  },
  'PAT-INP-050': {
    id: 'PAT-INP-050',
    screen: '특허 · 검색어 입력',
    component: '항목별 상세검색',
    display: '필드별 조합(펼침/접힘 · 필드 추가/확장 모달)',
    interaction: '필드 값 입력 시 검색식에 AND 누적',
    precondition: '항목별 상세검색 펼침 · 필드 선택됨',
    postcondition: '검색식에 CODE:(값) AND 누적(자유어는 선두만 범위 래핑, 직접 필드식 불변) · 실행 후 입력값만 비우고 구성 유지',
  },
  'PAT-INP-060': {
    id: 'PAT-INP-060',
    screen: '특허 · 검색어 입력',
    component: '검색 히스토리 (영역)',
    display: '최근 검색식 목록(공통·횡단 기능)',
    interaction: '↓ 액션별 (재검색 / 즐겨찾기 / 삭제)',
    precondition: '검색 1회 이상 실행됨',
    postcondition: '개별 액션(PAT-INP-061/062/063) 참조',
  },
  'PAT-INP-061': {
    id: 'PAT-INP-061',
    screen: '특허 · 검색어 입력',
    component: '항목 재검색',
    display: '히스토리 항목 행',
    interaction: '클릭',
    precondition: '기록 존재',
    postcondition: '선택 검색식으로 재실행',
  },
  'PAT-INP-062': {
    id: 'PAT-INP-062',
    screen: '특허 · 검색어 입력',
    component: '★즐겨찾기',
    display: '별 아이콘',
    interaction: '토글',
    precondition: '기록 존재',
    postcondition: '즐겨찾기 on/off 저장',
  },
  'PAT-INP-063': {
    id: 'PAT-INP-063',
    screen: '특허 · 검색어 입력',
    component: '삭제',
    display: '× 버튼 / 전체 삭제',
    interaction: '클릭',
    precondition: '기록 존재',
    postcondition: '해당(또는 전체) 기록 제거',
  },

  // ── 특허 · 결과 목록 ──
  'PAT-LST-010': { id: 'PAT-LST-010', screen: '특허 · 결과 목록', component: '상단 요약바', display: '적용 검색식 칩 · 총 건수 · → 논문으로', interaction: '교차검색 진입', precondition: '검색 실행 완료', postcondition: '총건수 표시 / 교차검색=논문 검색으로 검색어 이관·화면 전환' },
  'PAT-LST-020': { id: 'PAT-LST-020', screen: '특허 · 결과 목록', component: '결과 표·카드 (영역)', display: '컬럼: 체크박스·상태·문헌번호·원문PDF·발명의명칭(+새 탭)·출원인·출원일·IPC. 상태=평문(색 Badge 미사용)', interaction: '목록 렌더 / ↓ 액션별', precondition: '검색 실행 완료(응답 수신)', postcondition: '목록 렌더(totalCount·hits)' },
  'PAT-LST-021': { id: 'PAT-LST-021', screen: '특허 · 결과 목록', component: '행/카드 선택', display: '행/카드 본문', interaction: '클릭', precondition: '결과 행 존재', postcondition: '선택 인덱스 설정 · 미리보기 패널 오픈(내용은 보류(상세페이지))' },
  'PAT-LST-022': { id: 'PAT-LST-022', screen: '특허 · 결과 목록', component: '체크박스 선택', display: '행별 체크박스', interaction: '체크', precondition: '결과 행 존재', postcondition: '저장 대상 선택 상태 반영(→ 다중 선택 저장)' },
  'PAT-LST-030': { id: 'PAT-LST-030', screen: '특허 · 결과 목록', component: '패싯 필터바/사이드바 (영역)', display: '국가 · 권리상태 · 공개/등록(특허구분) · 출원연도 · IPC(Main/All) · 심판 유무 (출원인 대표명화 패싯은 이번 텀 미구현으로 제거)', interaction: '체크 후 실행', precondition: '결과 1건 이상 · 패싯 로드됨', postcondition: '체크한 축을 필터에 추가해 재검색 → 1페이지로 이동' },
  'PAT-LST-031': { id: 'PAT-LST-031', screen: '특허 · 결과 목록', component: 'IPC 패싯 Main/All 토글', display: 'IPC 패싯 팝오버 상단 [Main] [All] (기본 All)', interaction: '토글', precondition: 'IPC 패싯 열림', postcondition: 'Main=최신 대표 IPC(IPCM)만 / All=개정이력 포함 전체 IPC(IPC) 기준으로 코드목록·건수·매칭 전환' },
  'PAT-LST-080': { id: 'PAT-LST-080', screen: '특허 · 결과 목록', component: '중복제거 컨트롤', display: '상단 요약바 중복제거: 사용안함 / 등록 우선 / 공개 우선', interaction: '클릭', precondition: '검색 실행 완료', postcondition: '검색이 문헌번호 기준이라 동일 출원번호가 공개+등록 문헌으로 함께 잡힘 → 출원번호로 묶어 한 건만 남김(등록/공개 우선) · 1페이지로 이동' },
  'PAT-LST-040': { id: 'PAT-LST-040', screen: '특허 · 결과 목록', component: '정렬·perPage·페이지네이션', display: '출원일/공개일/등록일+방향 · perPage · 페이지', interaction: '변경 시 재요청(새 검색은 1페이지로)', precondition: '결과 존재', postcondition: 'orderByQuery/fetchOffset/fetchCount 갱신 후 재요청' },
  'PAT-LST-050': { id: 'PAT-LST-050', screen: '특허 · 결과 목록', component: 'CSV 다운로드', display: '버튼', interaction: '내보내기', precondition: '결과 1건 이상', postcondition: '현재 hits → CSV 생성·다운로드' },
  'PAT-LST-060': { id: 'PAT-LST-060', screen: '특허 · 결과 목록', component: '다중 선택 저장', display: '체크박스 + 선택 저장 버튼', interaction: '라이브러리 일괄 저장', precondition: '체크박스 1개 이상 선택', postcondition: '선택 특허를 라이브러리에 저장하고 체크 해제' },
  'PAT-LST-070': { id: 'PAT-LST-070', screen: '특허 · 결과 목록', component: '상태 표시(로딩/0건/오류)', display: '로딩·0건 안내·오류 메시지', interaction: '—', precondition: '검색 실행됨', postcondition: '응답 대기=로딩 · 0건=안내 · 실패=오류 메시지' },

  // ── 특허 · 상세페이지 ──
  'PAT-DET-010': { id: 'PAT-DET-010', screen: '특허 · 상세페이지', component: '헤더 액션 바 (영역)', display: '전체보기=로고·이전/다음·위치(n/총)·라이브러리 저장·탭 닫기 / 오버레이=이전/다음·위치·새 탭·저장·닫기', interaction: '↓ 액션별', precondition: '상세 진입', postcondition: '개별 액션(PAT-DET-011~013) 참조' },
  'PAT-DET-011': { id: 'PAT-DET-011', screen: '특허 · 상세페이지', component: '이전/다음 네비', display: '◀ ▶ + 위치(n/총)', interaction: '클릭(← →)', precondition: '목록 맥락 존재(인접 문서)', postcondition: '이전/다음 문서로 전환' },
  'PAT-DET-012': { id: 'PAT-DET-012', screen: '특허 · 상세페이지', component: '라이브러리 저장', display: '저장 버튼', interaction: '클릭', precondition: '—', postcondition: '현재 문서를 라이브러리에 저장' },
  'PAT-DET-013': { id: 'PAT-DET-013', screen: '특허 · 상세페이지', component: '닫기 / 새 탭 전체보기', display: '탭 닫기(전체보기)·닫기(오버레이)·새 탭(오버레이)', interaction: '클릭(Esc)', precondition: '—', postcondition: '오버레이 닫기(목록 복귀) / 새 탭으로 전체보기 열기' },
  'PAT-DET-020': { id: 'PAT-DET-020', screen: '특허 · 상세페이지', component: '제목 영역', display: '상태(평문) · 국가 · 문헌번호 · 발명의 명칭', interaction: '—', precondition: '상세 진입', postcondition: '문헌 식별 정보 표시' },
  'PAT-DET-021': { id: 'PAT-DET-021', screen: '특허 · 상세페이지', component: '원문 PDF 다운로드', display: '버튼', interaction: '클릭', precondition: '—', postcondition: '원문 PDF 다운로드(⚠목업 원문 URL 미정의)' },
  'PAT-DET-030': { id: 'PAT-DET-030', screen: '특허 · 상세페이지', component: '키워드 하이라이터 바', display: '검색어 키워드 칩(색상) + 이동(↑↓) + 접기', interaction: '검색어 유입 시 표시 · 본문 내 키워드 강조', precondition: '검색에서 진입(검색어 존재)', postcondition: '본문 키워드 하이라이트(client)' },
  'PAT-DET-040': { id: 'PAT-DET-040', screen: '특허 · 상세페이지', component: '앵커 탭 바', display: '서지·인명·요약·상세설명·청구범위·패밀리·인용·피인용·분류·기타', interaction: '탭 클릭', precondition: '상세 진입', postcondition: '해당 섹션으로 스크롤 · 활성 탭 표시' },
  'PAT-DET-050': { id: 'PAT-DET-050', screen: '특허 · 상세페이지', component: '서지사항', display: '문헌/출원/공개·공고/등록 번호·일자 · 원출원·국제출원 · 우선권주장일·심사청구일 · 존속만료·권리변동 · 최종처분·청구항수 · 출원구분·번역문 · 도면수·실시권등록일 · 지정국·서열목록 + 우선권 주장 목록 + 타임라인', interaction: '정독(스크롤)', precondition: '상세 진입', postcondition: '서지 표·우선권·타임라인 표시' },
  'PAT-DET-060': { id: 'PAT-DET-060', screen: '특허 · 상세페이지', component: '인명정보', display: '출원인/주소 · 특허고객번호(KR)·식별기호(JP) · 대표출원인 · 발명자/주소 · 대리인 · 심사관', interaction: '정독', precondition: '상세 진입', postcondition: '인명 표 표시' },
  'PAT-DET-070': { id: 'PAT-DET-070', screen: '특허 · 상세페이지', component: '요약', display: '요약 본문', interaction: '정독', precondition: '상세 진입', postcondition: '요약 표시' },
  'PAT-DET-080': { id: 'PAT-DET-080', screen: '특허 · 상세페이지', component: '상세설명', display: '기술분야·배경기술·해결하려는 과제·과제의 해결수단·발명의 효과·도면의 설명·구체적 내용', interaction: '정독', precondition: '상세 진입', postcondition: '상세설명(명세서 하위섹션) 표시' },
  'PAT-DET-090': { id: 'PAT-DET-090', screen: '특허 · 상세페이지', component: '청구범위 (영역)', display: '청구항(독립/종속 구조)', interaction: '↓ 액션별', precondition: '상세 진입', postcondition: '청구항 표시' },
  'PAT-DET-091': { id: 'PAT-DET-091', screen: '특허 · 상세페이지', component: '독립항/전체청구항 토글', display: '독립항 · 전체청구항 버튼', interaction: '클릭', precondition: '—', postcondition: '독립항만 / 전체 청구항 목록 전환' },
  'PAT-DET-100': { id: 'PAT-DET-100', screen: '특허 · 상세페이지', component: '패밀리 정보 (영역)', display: '국가별 건수 pill + 패밀리 문헌 목록(국가·번호·일자·명칭)', interaction: '↓ 국가 탭', precondition: '상세 진입', postcondition: '패밀리 표시' },
  'PAT-DET-101': { id: 'PAT-DET-101', screen: '특허 · 상세페이지', component: '국가 탭 필터', display: '전체 / 국가별 탭', interaction: '클릭', precondition: '패밀리 존재', postcondition: '선택 국가 패밀리만 필터 표시' },
  'PAT-DET-110': { id: 'PAT-DET-110', screen: '특허 · 상세페이지', component: '인용·피인용', display: '인용·피인용 목록(특허/비특허) + 선행기술문헌', interaction: '정독', precondition: '상세 진입', postcondition: '인용/피인용·선행기술 표시' },
  'PAT-DET-120': { id: 'PAT-DET-120', screen: '특허 · 상세페이지', component: '분류코드', display: 'IPC · CPC · 국가고유(FI/F-term/테마·UPC·EPC)', interaction: '정독', precondition: '상세 진입', postcondition: '분류 표시' },
  'PAT-DET-130': { id: 'PAT-DET-130', screen: '특허 · 상세페이지', component: '기타정보', display: '대리인 주소 · 권리변동 이력 · 권리이전 이력 · 행정처리(수발신) · 국가 R&D · 표준특허 · 심판', interaction: '정독', precondition: '상세 진입', postcondition: '있는 항목만 조건부 표시' },
  'PAT-DET-140': { id: 'PAT-DET-140', screen: '특허 · 상세페이지', component: '도면 패널', display: '대표도면 + 썸네일 목록 + 확대 뷰어 + 도면부호 설명', interaction: '도면 선택·확대', precondition: '도면 존재', postcondition: '선택 도면 확대 표시(⚠목업 도면 API 미정의)' },

  // ── 논문 · 검색어 입력 ──
  'PAP-INP-010': { id: 'PAP-INP-010', screen: '논문 · 검색어 입력', component: '발행연도 필터', display: '전체/최근1·5·10년 + 연도 from~to (국가 필터 없음)', interaction: '프리셋/범위 선택', precondition: '화면 진입', postcondition: 'yearFrom/yearTo(또는 years[]) 반영' },
  'PAP-INP-020': { id: 'PAP-INP-020', screen: '논문 · 검색어 입력', component: '검색어 범위 탭', display: '제목+초록 / 제목+초록+전문', interaction: '탭 전환', precondition: '화면 진입', postcondition: '선두 자유어 적용 범위 변경' },
  'PAP-INP-030': { id: 'PAP-INP-030', screen: '논문 · 검색어 입력', component: '검색식 입력창 + 검색/초기화 (영역)', display: '입력창 + 검색·초기화 버튼', interaction: '↓ 액션별', precondition: '—', postcondition: '개별 액션(PAP-INP-031/032) 참조' },
  'PAP-INP-031': { id: 'PAP-INP-031', screen: '논문 · 검색어 입력', component: '검색 실행', display: '검색 버튼', interaction: '클릭 / ⏎', precondition: '검색식 또는 항목별 필드에 값 1개 이상', postcondition: 'PaperSearchRequest 조립·POST → 논문 목록 전환 · 히스토리 추가' },
  'PAP-INP-032': { id: 'PAP-INP-032', screen: '논문 · 검색어 입력', component: '초기화', display: '초기화 버튼', interaction: '클릭', precondition: '—', postcondition: '입력값·필드 구성 복원' },
  'PAP-INP-040': { id: 'PAP-INP-040', screen: '논문 · 검색어 입력', component: '항목별 상세검색', display: '제목·초록·키워드·전문·저자 등(펼침/접힘)', interaction: '필드 값 입력 시 검색식 AND 누적', precondition: '상세검색 펼침·필드 선택됨', postcondition: '검색식 AND 누적 · 실행 후 입력값만 비움' },
  'PAP-INP-050': { id: 'PAP-INP-050', screen: '논문 · 검색어 입력', component: '검색 히스토리 (영역)', display: '최근 검색식 목록(특허와 동일 · 공통·횡단)', interaction: '↓ 액션별', precondition: '검색 1회 이상 실행됨', postcondition: '개별 액션(PAP-INP-051/052/053) 참조' },
  'PAP-INP-051': { id: 'PAP-INP-051', screen: '논문 · 검색어 입력', component: '항목 재검색', display: '히스토리 항목 행', interaction: '클릭', precondition: '기록 존재', postcondition: '선택 검색식으로 재실행' },
  'PAP-INP-052': { id: 'PAP-INP-052', screen: '논문 · 검색어 입력', component: '★즐겨찾기', display: '별 아이콘', interaction: '토글', precondition: '기록 존재', postcondition: '즐겨찾기 on/off 저장' },
  'PAP-INP-053': { id: 'PAP-INP-053', screen: '논문 · 검색어 입력', component: '삭제', display: '× 버튼 / 전체 삭제', interaction: '클릭', precondition: '기록 존재', postcondition: '해당(또는 전체) 기록 제거' },

  // ── 논문 · 결과 목록 ──
  'PAP-LST-010': { id: 'PAP-LST-010', screen: '논문 · 결과 목록', component: '상단 요약바', display: '검색식 칩 · 총 건수 · → 특허로', interaction: '교차검색 진입', precondition: '검색 실행 완료', postcondition: '총건수 표시 / 교차검색=특허 검색으로 검색어 이관·전환' },
  'PAP-LST-020': { id: 'PAP-LST-020', screen: '논문 · 결과 목록', component: '결과 카드 목록 (영역)', display: '제목(+대등제목) · 메타라인 · 초록("초록" 라벨) · 새 탭 열기 · 체크박스', interaction: '목록 렌더 / ↓ 액션별', precondition: '검색 실행 완료(응답 수신)', postcondition: '목록 렌더(totalCount·paper)' },
  'PAP-LST-021': { id: 'PAP-LST-021', screen: '논문 · 결과 목록', component: '카드 선택', display: '카드 본문', interaction: '클릭', precondition: '카드 존재', postcondition: '선택 인덱스 설정 · 미리보기 패널 오픈(내용은 보류(상세페이지))' },
  'PAP-LST-022': { id: 'PAP-LST-022', screen: '논문 · 결과 목록', component: '체크박스 선택', display: '카드별 체크박스', interaction: '체크', precondition: '카드 존재', postcondition: '저장 대상 선택 상태 반영(→ 다중 선택 저장)' },
  'PAP-LST-030': { id: 'PAP-LST-030', screen: '논문 · 결과 목록', component: '패싯 필터바', display: '저널 · 발행연도', interaction: '체크 후 실행', precondition: '결과 1건 이상 · 패싯 로드됨', postcondition: '저널/연도 필터 추가해 재검색 → 1페이지로' },
  'PAP-LST-040': { id: 'PAP-LST-040', screen: '논문 · 결과 목록', component: '정렬·perPage·페이지네이션', display: '매칭순/발행연도(최신·오래된) · perPage · 페이지', interaction: '변경 시 재요청', precondition: '결과 존재', postcondition: 'orderByQuery/fetchOffset 갱신 후 재요청' },
  'PAP-LST-050': { id: 'PAP-LST-050', screen: '논문 · 결과 목록', component: 'CSV 다운로드', display: '버튼', interaction: '내보내기', precondition: '결과 1건 이상', postcondition: '카드(제목·저자·저널·발행연도) → CSV 다운로드' },
  'PAP-LST-060': { id: 'PAP-LST-060', screen: '논문 · 결과 목록', component: '다중 선택 저장', display: '체크박스 + 선택 저장 버튼', interaction: '라이브러리 저장', precondition: '체크 1개 이상', postcondition: '선택 논문을 라이브러리에 저장하고 체크 해제' },
  'PAP-LST-070': { id: 'PAP-LST-070', screen: '논문 · 결과 목록', component: '상태 표시(로딩/0건/오류)', display: '로딩·0건 안내·오류 메시지', interaction: '—', precondition: '검색 실행됨', postcondition: '응답 대기=로딩 · 0건=안내 · 실패=오류 메시지' },

  // ── 공통 · 횡단 기능 (화면 요소에 걸쳐 실현 — 대표 위치에 부착) ──
  'COM-010': { id: 'COM-010', screen: '공통 · 횡단', component: '검색 히스토리', display: 'client(로컬 store)', interaction: '공통·횡단 기능', precondition: '검색 1회 이상 실행됨(기록 존재)', postcondition: '항목 선택 시 해당 검색식으로 재실행 · ★즐겨찾기 토글 저장(최대 100건)' },
  'COM-020': { id: 'COM-020', screen: '공통 · 횡단', component: 'URL 상태(SSOT)', display: '⚠ 프로토타입 미구현 — 연동 시 정의', interaction: '공통·횡단 기능', precondition: '검색 실행 or 쿼리 포함 URL 진입', postcondition: '상태를 URL에 직렬화 → 공유·뒤로가기·새로고침 복원' },
  'COM-030': { id: 'COM-030', screen: '공통 · 횡단', component: '재검색 재요청', display: 'client', interaction: '공통·횡단 기능', precondition: '동일 검색 조건으로 재실행', postcondition: 'URL 무변경이어도 명시적 invalidate·재요청' },
  'COM-040': { id: 'COM-040', screen: '공통 · 횡단', component: '라이브러리 저장', display: 'client(오버레이·상세 저장 버튼은 보류)', interaction: '공통·횡단 기능', precondition: '저장 대상(목록 체크 1개↑) 선택', postcondition: '선택 항목을 로컬 라이브러리에 저장하고 체크 해제' },
  'COM-050': { id: 'COM-050', screen: '공통 · 횡단', component: '특허 ↔ 논문 교차검색', display: 'client(별도 API 없음)', interaction: '공통·횡단 기능', precondition: '현재 검색어 존재', postcondition: '반대 도메인 검색으로 검색어 이관·화면 전환' },
  'COM-060': { id: 'COM-060', screen: '공통 · 횡단', component: 'CSV 내보내기', display: 'client', interaction: '공통·횡단 기능', precondition: '결과 1건 이상', postcondition: '현재 hits → CSV 생성·다운로드' },
  'COM-070': { id: 'COM-070', screen: '공통 · 횡단', component: '로딩/0건/오류 상태', display: 'client + 응답 성공/실패', interaction: '공통·횡단 기능', precondition: '검색 실행됨', postcondition: '응답 대기=로딩 · 0건=안내 · 실패=오류 메시지' },
  'COM-080': { id: 'COM-080', screen: '공통 · 횡단', component: '서비스 푸터(단일 규칙 · copykiller 통일)', display: 'copykiller.com 통일 리치 푸터 — ㈜무하유 회사정보/고객센터/콘텐츠(SNS) 3단 + 정책링크(개인정보처리방침·이용약관·연락처·FAQ) + Copyright © MUHAYU Inc. Since 2011', interaction: '정책/연락처/FAQ 링크 → 서비스 내 페이지', precondition: '각 페이지 스크롤 최하단에 1회(검색·결과·상세·정책·FAQ·홈)', postcondition: '오버레이 드로어 제외 · 새 탭 독립화면은 앱으로 이동 · 구 DetailFooter 폐지·일원화' },
  'COM-081': { id: 'COM-081', screen: '공통 · 횡단', component: '정책·FAQ 콘텐츠 페이지 (영역 확보)', display: '이용약관·개인정보처리방침·연락처(자리표시자) · FAQ(SEO/GEO/AEO 대비 골격)', interaction: '푸터 링크 진입 · 홈으로 복귀', precondition: '푸터에서 진입', postcondition: '확정 문구는 muhayu 제공본으로 대체 예정 · FAQ는 콘텐츠 순차 작성(현재 영역만)' },

  // ── 명세서 작성 (위저드 8단계 · AI 어시스턴트 · 에디터) — docs/기능정의서.md 「명세서 작성」 장과 1:1 ──
  'SPC-WIZ-010': { id: 'SPC-WIZ-010', screen: '명세서 · 위저드 공통 프레임', component: '새 명세서 작성 폼 (영역)', display: '제목 새 명세서 작성 · 작업 이름 (선택)(80자, "발명의 명칭을 입력하면 명세서 작성 중 자동 반영됩니다.") · 기술분야 (선택)(60자)', interaction: '↓ 액션별', precondition: '사이드바 「새 명세서」 진입', postcondition: '—' },
  'SPC-WIZ-011': { id: 'SPC-WIZ-011', screen: '명세서 · 위저드 공통 프레임', component: '명세서 작성 시작', display: 'primary 버튼(Enter)', interaction: '클릭', precondition: '항상 활성(빈 입력 허용 → 이름 새 명세서)', postcondition: '작업(type=spec) 생성 · 위저드 ① 업로드로 진입 · 사이드바 작업 목록에 추가' },
  'SPC-WIZ-012': { id: 'SPC-WIZ-012', screen: '명세서 · 위저드 공통 프레임', component: '취소', display: 'outlined 버튼', interaction: '클릭', precondition: '—', postcondition: '최근 명세서 작업으로 복귀(없으면 홈)' },
  'SPC-WIZ-020': { id: 'SPC-WIZ-020', screen: '명세서 · 위저드 공통 프레임', component: '스텝바 (영역, 48px)', display: '8개 칩 번호+단계명: 현재=brand 채움 · 완료=초록 ✓ · 잠김=회색 · 완료 구간 연결선 초록. 좌측 ↺ 처음부터 다시 시작', interaction: '↓ 액션별', precondition: '분석 시작 후(업로드 완료)', postcondition: '—' },
  'SPC-WIZ-021': { id: 'SPC-WIZ-021', screen: '명세서 · 위저드 공통 프레임', component: '단계 칩 이동', display: '툴팁 {단계}(으)로 이동 / 잠김 이전 단계를 먼저 완료하세요', interaction: '클릭', precondition: '현재 단계 이하(도달한 단계)만', postcondition: '해당 단계로 스크롤 · AI 어시스턴트 맥락 전환. 확정 상태는 바뀌지 않음(보기 이동)' },
  'SPC-WIZ-022': { id: 'SPC-WIZ-022', screen: '명세서 · 위저드 공통 프레임', component: '처음부터 다시 시작', display: '↺ 아이콘 · 확인 처음부터 다시 시작하면 모든 분석 내용이 삭제됩니다. 계속하시겠습니까?', interaction: '클릭 → 확인', precondition: '분석 시작 후', postcondition: '전 단계 확정·선택·후보·구성요소·중간명세서 초기화 → ① 업로드' },
  'SPC-WIZ-030': { id: 'SPC-WIZ-030', screen: '명세서 · 위저드 공통 프레임', component: '단계 안내(AI 메시지)', display: '각 단계 상단: 단계명 + 이 단계에서 할 일 1~2문장(예: 구성요소 — "구성요소의 명칭·정의를 확인하고 순서를 정한 뒤 부호(100, 200…)를 부여하세요. 채택한 구성요소가 청구항의 기준이 됩니다.") · ① 직후 업로드하신 문서를 분석했습니다. 발명의 설명 항목을 분석합니다.', interaction: '정독', precondition: '단계 도달', postcondition: '—' },
  'SPC-WIZ-040': { id: 'SPC-WIZ-040', screen: '명세서 · 위저드 공통 프레임', component: '확정 단계 접힘 요약 (영역)', display: '초록 ✓ + 단계명 + 1줄 요약(예: 제안기술 4/4 · 종래기술 2/2 항목 채택, 관련 이미지 2/2개 선택, 구성요소 4개 확정, 명세서 도면 2개 (도 1~2), 독립항 세트 · 종속항 확정, 7개 섹션)', interaction: '↓ 액션별', precondition: '단계 확정됨', postcondition: '—' },
  'SPC-WIZ-041': { id: 'SPC-WIZ-041', screen: '명세서 · 위저드 공통 프레임', component: '펼치기 / 접기', display: '버튼', interaction: '클릭', precondition: '확정 단계', postcondition: '내용 열람(읽기 전용·흐림) / 재접힘' },
  'SPC-WIZ-042': { id: 'SPC-WIZ-042', screen: '명세서 · 위저드 공통 프레임', component: '다시 선택', display: '✎ 버튼 · 이후 확정 단계가 있으면 확인 "{단계}"을/를 다시 선택하면 이후 단계({단계 · 단계})를 다시 확정해야 합니다. 계속할까요?', interaction: '클릭 → (확인)', precondition: '확정 단계', postcondition: '해당 단계 확정 해제 → 현재 단계로 복귀·스크롤. 이후 단계는 다시 확정 필요' },
  'SPC-WIZ-050': { id: 'SPC-WIZ-050', screen: '명세서 · 위저드 공통 프레임', component: '하단 액션 바 (영역)', display: '좌 ← 이전 · 우 주 동작 1개(단계별 패널이 등록: 다음 → / 독립항 세트 생성 → / 종속항 구성 → / 청구항 확정 → / 명세서 생성 →) · 비활성 시 좌측 힌트(예: 독립항 세트를 하나 선택하세요)', interaction: '↓ 액션별', precondition: '분석 시작 후', postcondition: '—' },
  'SPC-WIZ-051': { id: 'SPC-WIZ-051', screen: '명세서 · 위저드 공통 프레임', component: '← 이전', display: '툴팁 이전 단계 내용 보기', interaction: '클릭', precondition: '③ 이미지 선별 이후', postcondition: '이전 단계를 펼쳐 스크롤(확정 해제 없음)' },
  'SPC-WIZ-052': { id: 'SPC-WIZ-052', screen: '명세서 · 위저드 공통 프레임', component: '주 동작(확정·다음)', display: '단계별 라벨. 특수 확인: 이미지 0개 이미지 없이 다음 →(확인 "선택한 이미지가 없습니다. 이미지 없이 진행하면 명세서 도면과 도면 설명이 비게 됩니다. 계속할까요?") · 도면 0개 도면 없이 다음 →(확인) · 구성요소 미완 필드(확인 "보완이 필요한 구성요소 N개(…)가 있습니다. 영문명·상위어·정의가 비어 있으면 청구항·명세서에 그대로 반영됩니다. 그대로 진행할까요?") · 명칭 미선택 시 비활성', interaction: '클릭 → (확인)', precondition: '단계별(④는 명칭 값 필요, 나머지는 항상)', postcondition: '확정: 값 저장 → 파생(④ 명칭→발명정보 · ③ 대표 이미지 자동 · ⑤ 도면 채택 프리셋(선택 이미지 전부 채택 + 대표 1개) · ⑦ 도면의 간단한 설명 자동 생성 도 N은/는 {도면명}을/를 나타낸 도면이다.(대표도면)) → 0.9초 「다음 단계 분석 중…」 → 다음 단계 열림·스크롤. ⑧은 명세서 생성(→ SPC-WIZ-080)' },
  'SPC-WIZ-060': { id: 'SPC-WIZ-060', screen: '명세서 · 위저드 공통 프레임', component: '다음 단계 분석 로딩', display: '{다음 단계} 분석 중… + 불확정 진행바 + "AI가 항목을 분석하고 있습니다. 잠시만 기다려 주세요." · 하단 바 분석 중… 비활성', interaction: '대기', precondition: '확정 직후', postcondition: '다음 단계 표시' },
  'SPC-WIZ-070': { id: 'SPC-WIZ-070', screen: '명세서 · 위저드 공통 프레임', component: '분석 완료 화면', display: '모든 분석 항목이 확정되었습니다 / 확정된 내용을 바탕으로 명세서 초안을 편집하세요. · 편집 이력 있으면 이미 진행 중인 편집 내용이 있습니다 — 이어서 편집할 수 있습니다.', interaction: '에디터로 이동 → 클릭', precondition: '8단계 모두 확정', postcondition: '에디터 전환(사이드바 배지 에디터 편집 중)' },
  'SPC-WIZ-080': { id: 'SPC-WIZ-080', screen: '명세서 · 위저드 공통 프레임', component: '명세서 생성 오버레이', display: '전체 화면 모달: 스피너 · 명세서를 작성하고 있습니다 · 완료되면 에디터로 자동 이동합니다. · 취소. 단계 목록·진행 바·경과 시간 없음(사용자 결정 — 소요 시간을 드러내지 않음)', interaction: '대기 / 취소', precondition: '⑧ 명세서 생성 →', postcondition: '완료 시 실시예 섹션 추가 · ⑧ 확정 · 에디터 진입. 취소 시 토스트 명세서 생성을 취소했습니다(⑧ 유지)' },
  'SPC-WIZ-090': { id: 'SPC-WIZ-090', screen: '명세서 · 위저드 공통 프레임', component: 'AI 수정 공통 (영역)', display: '동일 형태·동일 위치 규칙 — 항목 우측 AI 수정(✈ 아이콘, 활성 시 brand 채움) · 패널 상단 전체 AI 수정 바 · 제안 카드', interaction: '↓ 액션별', precondition: '미확정 단계', postcondition: '—' },
  'SPC-WIZ-091': { id: 'SPC-WIZ-091', screen: '명세서 · 위저드 공통 프레임', component: 'AI 수정(인라인)', display: '지시 입력(Enter 전송 · Esc 닫기) · 수정 요청 / 취소 · 진행 수정안을 만들고 있습니다... · 취소 후 수정을 적용하지 않았습니다 — 지시를 고쳐 다시 요청할 수 있습니다 · 다중 대상(명칭·요약)은 카드 제목 명칭·요약 수정 제안', interaction: '지시 입력 → 수정 요청', precondition: '항목 채택됨 · 지시 비어 있지 않음', postcondition: '제안 카드(→ 093)' },
  'SPC-WIZ-092': { id: 'SPC-WIZ-092', screen: '명세서 · 위저드 공통 프레임', component: '전체 AI 수정 바', display: '패널 상단 한 줄: 지시 입력 + 전체 AI 수정(진행 수정안 생성 중...) · 제안 0건 변경이 필요 없다고 판단했습니다', interaction: '지시 입력 → 전송', precondition: '채택 항목 1개 이상', postcondition: '채택 항목 전부에 대한 제안 카드' },
  'SPC-WIZ-093': { id: 'SPC-WIZ-093', screen: '명세서 · 위저드 공통 프레임', component: '제안 확인 카드 · 적용 / 취소', display: '헤더 {제목} · N건 · 지시사항: … · 항목별 태그(수정/추가/삭제) · Before/After 단어 diff(삭제=빨강 취소선, 추가=초록) · ✦ 설명 · 취소 / 적용', interaction: '클릭', precondition: '제안 1건 이상', postcondition: '적용=항목 반영 + 토스트(…에 적용했습니다 / …을 수정했습니다) · 취소=수정을 적용하지 않았습니다' },
  'SPC-WIZ-100': { id: 'SPC-WIZ-100', screen: '명세서 · 위저드 공통 프레임', component: '삭제·덮어쓰기 확인 (공통)', display: '삭제: {대상} 삭제 / {대상}을/를 삭제할까요? 삭제 후에는 되돌릴 수 없습니다. / 삭제·취소(danger) · 덮어쓰기: 대상별 제목·본문 / 다시 생성·다시 분석 등·취소(primary). 조사(을/를·이/가·은/는)는 받침에 따라 자동', interaction: '확인/취소', precondition: '삭제·재생성 동작', postcondition: '확인 후에만 실행' },
  'SPC-WIZ-110': { id: 'SPC-WIZ-110', screen: '명세서 · 위저드 공통 프레임', component: '자동 저장·복원 (공통)', display: '표시 없음(0.4초 지연 저장)', interaction: '—', precondition: '상태 변경', postcondition: 'localStorage axp_spec_v3_<작업ID>에 단계·확정값·선택·발명정보·중간명세서·화면(위저드/에디터) 저장 → 재진입 시 복원. ⚠ 미저장: ⑦ 청구항 단계 내부(세트 선택·종속항 목록·권리범위 설정 — 확정 텍스트만 저장) · 구성요소 계층(depth)·미채택 항목 · 대화 이력' },
  'SPC-WIZ-120': { id: 'SPC-WIZ-120', screen: '명세서 · 위저드 공통 프레임', component: '사이드바 진행 배지', display: '작업 목록 메타 우측 2상태: 분석 중(brand, 툴팁에 N/8 단계명) / 명세서 생성완료(초록)', interaction: '정독(툴팁으로 세부 단계)', precondition: '명세서 작업', postcondition: '저장 상태에서 산출 — 생성완료 기준=명세서 생성 후 에디터 진입' },
  'SPC-UPL-010': { id: 'SPC-UPL-010', screen: '명세서 · ① 업로드', component: '업로드 드롭존 (영역)', display: '"직무발명서(PDF)를 업로드하면 AI가 발명 설명·이미지·명칭 후보를 자동으로 분석합니다." · 점선 박스 직무발명서 PDF를 여기에 끌어 놓으세요 / .pdf 지원', interaction: '↓', precondition: '작업 생성 직후', postcondition: '—' },
  'SPC-UPL-011': { id: 'SPC-UPL-011', screen: '명세서 · ① 업로드', component: '파일 선택', display: '파일 선택 버튼 / 박스 클릭 → 파일 대화상자(.pdf 단일)', interaction: '클릭 → 파일 선택', precondition: '—', postcondition: '분석 시작(→ 020). 작업 이름이 기본값이면 파일명(40자)으로 자동 명명. ⚠ 끌어 놓기(drag&drop) 핸들러는 미구현(문구만)' },
  'SPC-UPL-020': { id: 'SPC-UPL-020', screen: '명세서 · ① 업로드', component: '분석 로딩', display: '3단계 문구 PDF 텍스트 추출 중... → 발명 구성요소 파악 중... → 명세서 항목 분석 중... + 진행바', interaction: '대기', precondition: '파일 선택됨', postcondition: '발명 설명 항목·이미지·명칭 후보·구성요소 후보 생성 → ② 발명 설명 열림' },
  'SPC-DSC-010': { id: 'SPC-DSC-010', screen: '명세서 · ② 발명 설명', component: '발명 설명 항목 (영역)', display: 'lg 이상 2열(제안기술 · 종래기술, 헤더 채택 N/M) / 미만은 탭. 항목 카드: 라벨 배지(배경기술 · 구성(해결수단)/종래 구성 · 목적 · 효과 · 기타) + 본문 textarea', interaction: '↓ 액션별', precondition: '① 분석 완료', postcondition: '—' },
  'SPC-DSC-011': { id: 'SPC-DSC-011', screen: '명세서 · ② 발명 설명', component: '채택', display: '체크박스(툴팁 채택/채택 해제)', interaction: '토글', precondition: 'AI 생성 항목', postcondition: '미채택은 흐림·편집 불가 · 이후 단계(구성요소·청구항·명세서)에서 제외' },
  'SPC-DSC-012': { id: 'SPC-DSC-012', screen: '명세서 · ② 발명 설명', component: '순서·그룹 이동', display: '드래그 핸들(툴팁 "끌어서 순서 변경 (반대편 기술로 놓을 수 있음)") · ▲▼ · ← 제안기술로 / 종래기술로 →', interaction: '드래그 / 클릭', precondition: '—', postcondition: '같은 열 안 순서 변경 또는 반대 열로 이동' },
  'SPC-DSC-013': { id: 'SPC-DSC-013', screen: '명세서 · ② 발명 설명', component: '본문 편집', display: 'textarea(자동 높이)', interaction: '입력', precondition: '채택됨', postcondition: '발명정보에 즉시 반영' },
  'SPC-DSC-014': { id: 'SPC-DSC-014', screen: '명세서 · ② 발명 설명', component: 'AI 수정', display: 'AI 수정 → 인라인 지시(예: "구성요소의 결합 관계를 더 구체적으로 써줘") → 제안 카드 → 적용/취소', interaction: '→ SPC-WIZ-091/093', precondition: '채택됨 · 표 항목 아님', postcondition: '항목 본문 교체 · 토스트 항목을 수정했습니다' },
  'SPC-DSC-015': { id: 'SPC-DSC-015', screen: '명세서 · ② 발명 설명', component: '삭제 ✕', display: '확인 "{앞 40자…}" 항목을 삭제할까요?', interaction: '클릭 → 확인', precondition: '직접 추가한 항목(AI 항목은 채택 해제로 제외)', postcondition: '항목 제거' },
  'SPC-DSC-016': { id: 'SPC-DSC-016', screen: '명세서 · ② 발명 설명', component: '항목 추가', display: '열 하단: 라벨 select(배경기술 · 구성(해결수단) · 목적 · 효과 · 기타) + 내용 입력(Enter) + 추가', interaction: '입력 → 추가', precondition: '내용 비어 있지 않음', postcondition: '해당 열 끝에 항목 추가(삭제 가능)' },
  'SPC-DSC-017': { id: 'SPC-DSC-017', screen: '명세서 · ② 발명 설명', component: '표 항목', display: '표 캡션 배지 + 캡션 + 표(원문 HTML) — 읽기 전용', interaction: '정독', precondition: '추출 항목 type=table', postcondition: '원문 그대로 명세서에 반영(AI 수정·편집 불가)' },
  'SPC-DSC-030': { id: 'SPC-DSC-030', screen: '명세서 · ② 발명 설명', component: '↻ 다시 정제', display: '전체 AI 수정 바 우측 하단 버튼 · 덮어쓰기 확인 다이얼로그', interaction: '클릭 → 확인', precondition: '미확정', postcondition: '제안·종래 항목을 정제본으로 대체 (API description/refined)' },
  'SPC-DSC-020': { id: 'SPC-DSC-020', screen: '명세서 · ② 발명 설명', component: '전체 AI 수정 바', display: '제목 발명 설명 수정 제안 · 지시 예 "종래 기술의 문제점을 배경/한계로 나눠서 정리해줘"', interaction: '→ SPC-WIZ-092/093', precondition: '채택 항목(표 제외) 1개 이상', postcondition: '채택 항목 전부 제안 → 적용 시 발명 설명에 적용했습니다' },
  'SPC-IMG-010': { id: 'SPC-IMG-010', screen: '명세서 · ③ 이미지 선별', component: '이미지 목록 (영역)', display: '추출된 이미지 N개 · 선택 M개 · 안내 "관련 있는 이미지를 선택하세요. 미선택(흐림)은 맥락에서 제외됩니다. 대표 이미지 1개를 지정하면 이후 생성의 기준이 됩니다." · 카드: 썸네일(BBox 크롭) · 이미지 N(툴팁 원본 기호) · 분류 · 이름', interaction: '↓ 액션별', precondition: '② 확정', postcondition: '—' },
  'SPC-IMG-011': { id: 'SPC-IMG-011', screen: '명세서 · ③ 이미지 선별', component: '선택', display: '선택 체크박스(툴팁 "선택 (맥락에 사용)" / "선택 해제 (맥락에서 제외)")', interaction: '토글', precondition: '미확정', postcondition: '미선택=흐림 · 해제 시 대표 지정도 해제' },
  'SPC-IMG-012': { id: 'SPC-IMG-012', screen: '명세서 · ③ 이미지 선별', component: '대표', display: '대표 라디오(툴팁 "대표 이미지 (1개만)")', interaction: '클릭(재클릭 해제)', precondition: '선택된 이미지', postcondition: '1개만 대표 · 확정 시 미지정이면 첫 선택 이미지가 대표' },
  'SPC-IMG-013': { id: 'SPC-IMG-013', screen: '명세서 · ③ 이미지 선별', component: '분류', display: 'select 제안기술 · 종래기술 · 배경 · 효과 · 기타(툴팁 "분류 변경")', interaction: '선택', precondition: '미확정', postcondition: 'Drawing.detail.label 변경(확정 후 배지로 표시)' },
  'SPC-IMG-014': { id: 'SPC-IMG-014', screen: '명세서 · ③ 이미지 선별', component: '삭제 ✕', display: '확인 「이미지 삭제」 "{이름}"을/를 목록에서 삭제하시겠습니까?', interaction: '클릭 → 확인', precondition: '미확정', postcondition: '목록에서 제거' },
  'SPC-IMG-015': { id: 'SPC-IMG-015', screen: '명세서 · ③ 이미지 선별', component: '새 탭에서 열기', display: '↗(호버 시)', interaction: '클릭', precondition: '이미지 데이터 있음', postcondition: '크롭 결과 PNG를 새 탭에 표시' },
  'SPC-IMG-020': { id: 'SPC-IMG-020', screen: '명세서 · ③ 이미지 선별', component: '이미지 추가 (로컬 업로드)', display: '이미지 추가 (로컬 업로드) (image/*)', interaction: '파일 선택', precondition: '미확정', postcondition: '목록 끝에 추가(선택됨 · 도면 미채택 · 이름=파일명)' },
  'SPC-TTL-010': { id: 'SPC-TTL-010', screen: '명세서 · ④ 명칭·요약', component: '명칭 후보 카드 (영역)', display: '후보별: 라디오 + 명칭 · 요약 행 · 추천 이유(이탤릭) · 우측 AI 수정. A/B/C 같은 기호 없음(항목 자체가 선택지)', interaction: '↓ 액션별', precondition: '③ 확정', postcondition: '—' },
  'SPC-TTL-011': { id: 'SPC-TTL-011', screen: '명세서 · ④ 명칭·요약', component: '후보 선택', display: '카드/라디오 클릭(첫 후보 기본 선택)', interaction: '클릭', precondition: '—', postcondition: '선택 명칭·요약이 발명정보(title/summary)로 전파 → 하단 다음 → 활성' },
  'SPC-TTL-012': { id: 'SPC-TTL-012', screen: '명세서 · ④ 명칭·요약', component: 'AI 수정(명칭·요약)', display: '툴팁 "명칭과 요약을 AI로 수정" → 인라인 지시(예: "방법(method) 청구 관점으로 바꿔줘") → 카드 제목 명칭·요약 수정 제안(대상 2개) → 적용/취소', interaction: '→ SPC-WIZ-091/093', precondition: '—', postcondition: '해당 후보의 명칭·요약 교체 · 토스트 명칭·요약을 수정했습니다' },
  'SPC-TTL-013': { id: 'SPC-TTL-013', screen: '명세서 · ④ 명칭·요약', component: '추천 이유', display: '후보별 이유 문장', interaction: '정독', precondition: 'API 응답에 이유 있음', postcondition: '—' },
  'SPC-TTL-020': { id: 'SPC-TTL-020', screen: '명세서 · ④ 명칭·요약', component: '직접 입력', display: '라디오 직접 입력 + 명칭 textarea + 요약 (선택 — 요약서에 반영)', interaction: '입력', precondition: '—', postcondition: '후보 선택 해제 · 입력값이 명칭/요약으로 전파' },
  'SPC-TTL-030': { id: 'SPC-TTL-030', screen: '명세서 · ④ 명칭·요약', component: '↻ 후보 다시 생성', display: '버튼', interaction: '클릭', precondition: '—', postcondition: '후보 목록 재생성 · 토스트 명칭 후보를 다시 생성했습니다' },
  'SPC-CMP-010': { id: 'SPC-CMP-010', screen: '명세서 · ⑤ 구성요소', component: '구성요소 목록 (영역)', display: '헤더 구성요소 목록 · 카드: 채택 체크 · 드래그 핸들 · 부호 배지(100/—) · 보완 필요 배지 · 필드(명칭 · 명칭 영문명 · 상위어 · 상위어 영문명 · 정의) · 우측 AI 수정/▲▼/하위로→ ←상위로 · 계층별 16px 들여쓰기', interaction: '↓ 액션별', precondition: '④ 확정', postcondition: '—' },
  'SPC-CMP-011': { id: 'SPC-CMP-011', screen: '명세서 · ⑤ 구성요소', component: '채택', display: '체크박스', interaction: '토글', precondition: '미확정', postcondition: '미채택=흐림·부호 없음·청구항 기준에서 제외. 이름 없는 미채택 항목은 즉시 제거(개별 삭제 버튼 없음)' },
  'SPC-CMP-012': { id: 'SPC-CMP-012', screen: '명세서 · ⑤ 구성요소', component: '순서·계층', display: '드래그 / ▲▼ / 하위로 (→)·상위로 (←)(최대 3단계)', interaction: '드래그·클릭', precondition: '하위로: 바로 위 항목이 같은/상위 계층', postcondition: '순서·depth 변경 → 부호 자동 재계산(100·200 / 110·120 / 111·112)' },
  'SPC-CMP-013': { id: 'SPC-CMP-013', screen: '명세서 · ⑤ 구성요소', component: '필드 편집 · 명칭 변경=전역 치환', display: '5개 입력. 명칭은 포커스 아웃 시 이전 이름과 비교', interaction: '입력 · 명칭 blur', precondition: '미확정', postcondition: '명칭이 바뀌면 발명 설명·명칭·요약·청구항·중간명세서·에디터 본문(저장본) 의 모든 언급 치환(부호 보존 · 긴 이름 우선) + 토스트 ’A’ → ’B’ — 본문 N곳도 함께 바꿨습니다(언급 없으면 ’A’ → ’B’로 바꿨습니다)' },
  'SPC-CMP-014': { id: 'SPC-CMP-014', screen: '명세서 · ⑤ 구성요소', component: 'AI 수정', display: '툴팁 "이 구성요소를 AI로 수정" → 인라인(예: "정의에 센서 융합 기능을 보강해줘") → 제안 → 적용/취소', interaction: '→ SPC-WIZ-091/093', precondition: '채택됨', postcondition: '정의 교체 · 토스트 구성요소를 수정했습니다' },
  'SPC-CMP-015': { id: 'SPC-CMP-015', screen: '명세서 · ⑤ 구성요소', component: '보완 필요 배지', display: '툴팁 "영문명·상위어·정의 중 빈 항목이 있습니다. 채워 넣거나 채택을 해제하세요."', interaction: '정독', precondition: '채택 항목에 빈 필드', postcondition: '하단 다음 → 시 확인 다이얼로그(→ SPC-WIZ-052). 현행 유지 결정(형식 검사)' },
  'SPC-CMP-020': { id: 'SPC-CMP-020', screen: '명세서 · ⑤ 구성요소', component: '목록 도구 (영역)', display: '헤더 우측: ↻ 다시 분석 · AI 추가 · 부호 자동 부여 · 하단 구성요소 추가 · 안내 "순서 조정 후 부호 자동 부여를 클릭하면 100, 200... 번호가 할당됩니다."', interaction: '↓ 액션별', precondition: '미확정', postcondition: '—' },
  'SPC-CMP-021': { id: 'SPC-CMP-021', screen: '명세서 · ⑤ 구성요소', component: '↻ 다시 분석', display: '툴팁 "AI 추출을 다시 실행" · 확인 「구성요소 다시 분석」 현재 구성요소 목록(명칭·정의·순서·부호)이 AI 추출 결과로 대체됩니다. 계속할까요?', interaction: '클릭 → 확인', precondition: '진행 중 아님', postcondition: '목록 전체 교체 · 토스트 구성요소를 다시 분석했습니다' },
  'SPC-CMP-022': { id: 'SPC-CMP-022', screen: '명세서 · ⑤ 구성요소', component: 'AI 추가', display: '토글 → 입력 바 "추가할 구성요소를 설명하세요. 예: 사용자 인증을 처리하는 보안 모듈 (Enter로 추가)" + 추가', interaction: '입력 → 추가', precondition: '입력 비어 있지 않음', postcondition: '설명 앞부분을 명칭으로 한 항목 추가(나머지 필드 비움 → 보완 필요)' },
  'SPC-CMP-023': { id: 'SPC-CMP-023', screen: '명세서 · ⑤ 구성요소', component: '부호 자동 부여', display: 'primary 버튼', interaction: '클릭', precondition: '—', postcondition: '채택 항목에 순서·계층 기준 부호 부여(이용자 도구 — 사용자 결정)' },
  'SPC-CMP-024': { id: 'SPC-CMP-024', screen: '명세서 · ⑤ 구성요소', component: '구성요소 추가', display: '+ 버튼', interaction: '클릭', precondition: '—', postcondition: '빈 카드 추가 · 명칭 입력 포커스' },
  'SPC-CMP-030': { id: 'SPC-CMP-030', screen: '명세서 · ⑤ 구성요소', component: '전체 AI 수정 바', display: '제목 구성요소 수정 제안 · 지시 예 "가이드 레일 설명에 설치 간격 내용을 보강해줘"', interaction: '→ SPC-WIZ-092/093', precondition: '채택 항목 1개 이상', postcondition: '채택 항목 정의 전부 제안 → 구성요소에 적용했습니다' },
  'SPC-DRW-010': { id: 'SPC-DRW-010', screen: '명세서 · ⑥ 명세서 도면', component: '도면 목록 (영역)', display: '관련 이미지 N개 · 명세서 도면 M개 · 안내 "이미지 선별에서 고른 이미지는 기본으로 채택되어 있습니다. 명세서에 넣지 않을 이미지는 참고만으로 바꾸세요 — 채택 도면은 "도 N" 번호가 붙고 CAD 변환 대상이 됩니다." · 카드: 썸네일 · 도 N(채택 순 자동 번호) · 분류 · 이름', interaction: '↓ 액션별', precondition: '⑤ 확정(선택 이미지 전부 채택 + 대표 1개 프리셋)', postcondition: '—' },
  'SPC-DRW-011': { id: 'SPC-DRW-011', screen: '명세서 · ⑥ 명세서 도면', component: '채택 / 참고만', display: '세그먼트 도 N(또는 도면 채택) ｜ 참고만(툴팁: "명세서 도면으로 채택 (도 N 번호 부여 · CAD 변환 대상)" / "명세서에 넣지 않고 AI 참고용(맥락)으로만 사용")', interaction: '클릭', precondition: '미확정', postcondition: '채택 순서로 도 N 재번호 · 참고만은 번호 없음·대표 해제' },
  'SPC-DRW-012': { id: 'SPC-DRW-012', screen: '명세서 · ⑥ 명세서 도면', component: '대표도면', display: '대표 라디오(툴팁 "대표도면 (1개만)")', interaction: '클릭', precondition: '채택 도면', postcondition: '요약서 【대표도】 도 N · 도면 설명 (대표도면)' },
  'SPC-DRW-013': { id: 'SPC-DRW-013', screen: '명세서 · ⑥ 명세서 도면', component: '분류', display: 'select 제안기술 · 종래기술 · 배경 · 효과 · 기타', interaction: '선택', precondition: '미확정', postcondition: '라벨 변경(에디터 도면 카드 배지와 동일 표기)' },
  'SPC-DRW-014': { id: 'SPC-DRW-014', screen: '명세서 · ⑥ 명세서 도면', component: '도면 편집기', display: '도면 편집기에서 조정·변환 ↗(툴팁 "범위 조정·CAD 변환")', interaction: '클릭', precondition: '채택 도면 · 미확정', postcondition: '새 탭 도면 편집기 → 결과 수신: 범위(BBox) 갱신 · 이름/설명/라벨 갱신 · CAD 변환 완료 시 썸네일 교체' },
  'SPC-DRW-015': { id: 'SPC-DRW-015', screen: '명세서 · ⑥ 명세서 도면', component: 'CAD 변환 완료 배지', display: '초록 CAD 변환 완료(툴팁 "도면 편집기에서 CAD 변환 결과를 반영했습니다")', interaction: '정독', precondition: '편집기 변환 결과 수신', postcondition: '—' },
  'SPC-CLM-010': { id: 'SPC-CLM-010', screen: '명세서 · ⑦ 청구항', component: '권리범위 설정 (영역)', display: '제목 권리범위 설정 · 용어 도움말("추상화 수준은 청구항을 얼마나 넓게 쓸지…, 청구항 구성은 어떤 종류의 항으로 청구할지 — 장치항·방법항·제조항·조성물항")', interaction: '↓ 액션별', precondition: '⑥ 확정', postcondition: '—' },
  'SPC-CLM-011': { id: 'SPC-CLM-011', screen: '명세서 · ⑦ 청구항', component: '추상화 수준', display: '버튼 넓은 / 균형 / 한정(툴팁: 청구 범위 최대화 — 심사 대응 필요 / 등록 가능성과 보호 범위 균형 / 구체 구성 한정 — 등록 용이) · 기본 균형', interaction: '클릭', precondition: '미확정', postcondition: '생성 결과·선택 초기화(재생성 필요)' },
  'SPC-CLM-012': { id: 'SPC-CLM-012', screen: '명세서 · ⑦ 청구항', component: '청구항 구성 슬롯', display: '청구항 구성 (n/3) · 슬롯: 카테고리 select(장치항 · 방법항 · 제조항 · 조성물항) + 방향·강조점 입력(선택) + ✕ · + 청구항 추가 · 기본 장치항+방법항', interaction: '선택·입력 · 추가/삭제', precondition: '2~3개 유지(2개 이하 삭제 불가 툴팁 "최소 2개") · 삭제 시 입력값 있으면 확인', postcondition: '카테고리 변경/추가/삭제는 생성 결과 초기화' },
  'SPC-CLM-013': { id: 'SPC-CLM-013', screen: '명세서 · ⑦ 청구항', component: '추가 지시사항', display: '입력(예: "방법 청구항 위주로 작성해줘") · 안내 "기본 설정(균형 · 장치항+방법항) 그대로 생성해도 됩니다. 준비되면 하단의 독립항 세트 생성 →을 누르세요."', interaction: '입력', precondition: '생성 전', postcondition: '생성 요청에 전달(⚠ 목업에서는 미반영)' },
  'SPC-CLM-020': { id: 'SPC-CLM-020', screen: '명세서 · ⑦ 청구항', component: '독립항 세트 (영역)', display: '하단 독립항 세트 생성 → 후: 안내 "설정한 권리범위·구성으로 독립항 세트를 생성했습니다. 1개를 선택하면 종속항을 구성합니다." · 세트 카드 세트 N · {권리범위} + 장치항 + 방법항 · 구성요소 K개 · 설명 · 항별 카테고리 배지 + 본문(구성요소 하이라이트)', interaction: '↓ 액션별', precondition: '생성됨', postcondition: '조건 불일치 선택한 조건에 맞는 세트가 없습니다.' },
  'SPC-CLM-021': { id: 'SPC-CLM-021', screen: '명세서 · ⑦ 청구항', component: '세트 선택', display: '카드/라디오 → 선택됨', interaction: '클릭', precondition: '미확정', postcondition: '선택 세트 항은 편집 가능 · 하단 종속항 구성 → 활성(미선택 힌트 독립항 세트를 하나 선택하세요)' },
  'SPC-CLM-022': { id: 'SPC-CLM-022', screen: '명세서 · ⑦ 청구항', component: '독립항 편집 · AI 수정', display: 'textarea(선택 세트) · AI 수정(예: "권리범위를 조금 더 넓혀줘") → 제안 → 적용/취소', interaction: '입력 / → SPC-WIZ-091/093', precondition: '선택 세트 · 미확정', postcondition: '본문 교체 · 토스트 독립항을 수정했습니다' },
  'SPC-CLM-030': { id: 'SPC-CLM-030', screen: '명세서 · ⑦ 청구항', component: '종속항 (영역)', display: '요약 {권리범위} — 독립항 N개, 종속항 M개 · 독립항별 그룹: 청구항 N + 카테고리 + 본문 → 종속항 · 채택 K + ↻ 다시 생성 → 종속항 행(체크 · 종속항 N(전체 통산 번호) · 본문(인용 제N항에 있어서 자동 보정) · 호버 시 AI 수정/✕)', interaction: '↓ 액션별', precondition: '종속항 구성 →', postcondition: '하단 청구항 확정 →' },
  'SPC-CLM-031': { id: 'SPC-CLM-031', screen: '명세서 · ⑦ 청구항', component: '← 세트 다시 선택', display: '링크 버튼', interaction: '클릭', precondition: '미확정', postcondition: '독립항 세트 화면으로(종속항 상태 유지)' },
  'SPC-CLM-032': { id: 'SPC-CLM-032', screen: '명세서 · ⑦ 청구항', component: '종속항 분량 · 생성 지시', display: '적게/보통/많이(claim_count_level) + 생성 지시사항 입력(선택, API instruction)', interaction: '클릭·입력', precondition: '미확정', postcondition: '선택 세트 전체 종속항 재생성' },
  'SPC-CLM-033': { id: 'SPC-CLM-033', screen: '명세서 · ⑦ 청구항', component: '종속항 채택', display: '체크박스(채택/채택 해제)', interaction: '토글', precondition: '미확정', postcondition: '미채택=흐림 · 번호·요약 갱신 · 확정 텍스트에서 제외' },
  'SPC-CLM-034': { id: 'SPC-CLM-034', screen: '명세서 · ⑦ 청구항', component: 'AI 수정', display: '인라인(예: "한정 요소를 더 구체화해줘") → 제안 → 적용/취소', interaction: '→ SPC-WIZ-091/093', precondition: '채택 종속항', postcondition: '본문 교체 · 토스트 종속항을 수정했습니다' },
  'SPC-CLM-035': { id: 'SPC-CLM-035', screen: '명세서 · ⑦ 청구항', component: '삭제 ✕', display: '확인 「종속항 N 삭제」 종속항 N을/를 삭제할까요? 명세서에서 빼기만 하려면 체크를 해제하세요.', interaction: '클릭 → 확인', precondition: '미확정', postcondition: '항 제거' },
  'SPC-CLM-036': { id: 'SPC-CLM-036', screen: '명세서 · ⑦ 청구항', component: '↻ 다시 생성', display: '툴팁 "이 독립항의 종속항을 다시 생성" · 확인 「종속항 다시 생성」 청구항 N의 종속항이 새 초안으로 대체됩니다(편집·채택 내용 소실). 계속할까요?', interaction: '클릭 → 확인', precondition: '미확정', postcondition: '해당 독립항 종속항 교체' },
  'SPC-CLM-037': { id: 'SPC-CLM-037', screen: '명세서 · ⑦ 청구항', component: '종속항 추가', display: '입력 제N항에 있어서, ...(Enter) + 추가', interaction: '입력 → 추가', precondition: '내용 비어 있지 않음', postcondition: '채택 상태로 추가' },
  'SPC-CLM-038': { id: 'SPC-CLM-038', screen: '명세서 · ⑦ 청구항', component: '전체 AI 수정 바', display: '제목 종속항 수정 제안 · 지시 예 "각 독립항당 한정 요소를 다양하게 / 3항을 더 넓게"', interaction: '→ SPC-WIZ-092/093', precondition: '채택 종속항 1개 이상', postcondition: '채택 종속항 전부 제안 → 종속항에 적용했습니다' },
  'SPC-CLM-040': { id: 'SPC-CLM-040', screen: '명세서 · ⑦ 청구항', component: '선행 근거 확인 경고', display: '선행 근거 확인: ’{용어}’이/가 제N항에 없습니다.', interaction: '—', precondition: '이번 버전 제외 — ENABLE_ANTECEDENT_CHECK=false(API에 검증 기능 없음, 사용자 결정)', postcondition: '미노출' },
  'SPC-MID-010': { id: 'SPC-MID-010', screen: '명세서 · ⑧ 중간명세서', component: '중간명세서 섹션 (영역)', display: '안내 "AI가 중간명세서를 초안 작성했습니다. 각 항목을 직접 편집하거나 단락을 추가·삭제할 수 있습니다." · 섹션 제목 {섹션} (N개 단락) · 단락(구성요소 하이라이트) · 호버 시 AI 수정 / ✎ 직접 편집 / ✕', interaction: '↓ 액션별', precondition: '⑦ 확정', postcondition: '—' },
  'SPC-MID-011': { id: 'SPC-MID-011', screen: '명세서 · ⑧ 중간명세서', component: '직접 편집', display: '✎(툴팁 "직접 편집") → textarea + 취소 / 저장', interaction: '클릭 → 입력 → 저장', precondition: '미확정', postcondition: '단락 교체(취소 시 폐기)' },
  'SPC-MID-012': { id: 'SPC-MID-012', screen: '명세서 · ⑧ 중간명세서', component: 'AI 수정', display: '인라인 ’{섹션}’ 단락을 어떻게 수정할지 지시해주세요 → 제안 → 적용/취소', interaction: '→ SPC-WIZ-091/093', precondition: '미확정', postcondition: '단락 교체 · 토스트 단락을 수정했습니다' },
  'SPC-MID-013': { id: 'SPC-MID-013', screen: '명세서 · ⑧ 중간명세서', component: '삭제 ✕', display: '확인 「’{섹션}’ 단락 삭제」 ’{섹션}’ 단락을/를 삭제할까요? 삭제 후에는 되돌릴 수 없습니다.', interaction: '클릭 → 확인', precondition: '미확정', postcondition: '단락 제거' },
  'SPC-MID-015': { id: 'SPC-MID-015', screen: '명세서 · ⑧ 중간명세서', component: '도면 설명 지시 · 다시 생성', display: '도면의 간단한 설명 섹션 헤더: 생성 지시 입력(API instruction) + ↻ 다시 생성(덮어쓰기 확인)', interaction: '입력 → 클릭 → 확인', precondition: '미확정 · 채택 도면 존재', postcondition: '채택 도면 기준 섹션 대체 — 같은 분류 연속은 묶음 설명(API idxs)' },
  'SPC-MID-014': { id: 'SPC-MID-014', screen: '명세서 · ⑧ 중간명세서', component: '단락 추가', display: '섹션 하단 입력 단락 추가...(Enter) + 추가', interaction: '입력 → 추가', precondition: '내용 비어 있지 않음', postcondition: '섹션 끝에 단락 추가' },
  'SPC-MID-020': { id: 'SPC-MID-020', screen: '명세서 · ⑧ 중간명세서', component: '생성 지시 · ↻ 중간명세서 다시 생성', display: '지시 입력 "생성 지시·선호 사항 (선택) — 예: 배경기술은 규제 동향부터 서술해줘 / 효과는 정량 수치를 강조해줘" · ↻ 중간명세서 다시 생성(진행 생성 중...) · 확인 「중간명세서 다시 생성」 현재 편집한 단락 내용이 새 초안으로 대체됩니다. 계속할까요?', interaction: '입력 → 클릭 → 확인', precondition: '진행 중 아님', postcondition: '전 섹션 초안 대체 · 토스트 중간명세서를 다시 생성했습니다' },
  'SPC-MID-030': { id: 'SPC-MID-030', screen: '명세서 · ⑧ 중간명세서', component: '명세서 생성 → (하단 주 동작)', display: '안내 "편집을 마쳤으면 하단의 명세서 생성 →을 누르세요. AI가 구성요소·도면·청구항을 기반으로 실시예를 포함한 명세서 초안을 만들고 에디터로 이동합니다."', interaction: '클릭', precondition: '미확정', postcondition: '생성 오버레이(→ SPC-WIZ-080) → 실시예 섹션 추가 · ⑧ 확정 · 에디터 진입' },
  'SPC-AST-010': { id: 'SPC-AST-010', screen: '명세서 · AI 어시스턴트 — 작성 안내', component: 'AI 어시스턴트 패널 (영역)', display: '우측 320px(드래그로 320~700px) · 헤더 AI 어시스턴트(+확정됨 배지) → 「확정 내용」 정보 영역 → 「대화 · 작성 안내」 대화 영역 → 입력창. 두 영역은 회색 제목 바로 구분. 모바일은 FAB AI 어시스턴트 → 하단 시트', interaction: '질문 입력', precondition: '분석 시작 후', postcondition: '단계 전환 시 대화 초기화(단계 맥락)' },
  'SPC-AST-011': { id: 'SPC-AST-011', screen: '명세서 · AI 어시스턴트 — 작성 안내', component: '확정 내용 (정보 영역)', display: '제목 바 ✓ 확정 내용 · N/8 단계 · 확정 단계별 단계명 : 요약(발명의 설명 · 이미지 선별 · 발명의 명칭 · 구성요소 · 명세서 도면 · 청구항 · 중간명세서) · 없으면 "단계를 확정하면 여기에 요약이 쌓입니다." · 안내 "항목 수정은 각 항목의 AI 수정 버튼으로 그 자리에서 요청하세요."', interaction: '정독', precondition: '—', postcondition: '—' },
  'SPC-AST-012': { id: 'SPC-AST-012', screen: '명세서 · AI 어시스턴트 — 작성 안내', component: '대화 · 작성 안내 (대화 영역)', display: '제목 바 대화 · 작성 안내 — 단계 진행·작성 방법 질문 · 메시지 목록', interaction: '정독', precondition: '—', postcondition: '—' },
  'SPC-AST-030': { id: 'SPC-AST-030', screen: '명세서 · AI 어시스턴트 — 작성 안내', component: 'AI 응답(의도 배지)', display: '배지(답변 · 방향 확인 · 미지원 등) + 본문. 규칙: 질문 → 키워드 답변(청구항/명칭/구성요소/도면) 또는 일반 답변 · 수정 지시 → "항목 수정은 본문 각 항목의 "AI 수정" 버튼을 눌러 그 자리에서 지시해 주세요…" · 다단계 → "여러 단계 작업(플랜)은 명세서 에디터의 AI 어시스턴트에서 진행해 주세요." · 외부 검색 등 → 미지원', interaction: '정독', precondition: '질문 전송됨', postcondition: '—' },
  'SPC-AST-033': { id: 'SPC-AST-033', screen: '명세서 · AI 어시스턴트 — 작성 안내', component: '방향 선택지(clarify)', display: '칩', interaction: '칩 클릭', precondition: '응답에 선택지 포함(⚠ 현 목업 라우팅에서는 발생 경로 없음)', postcondition: '선택 후 답변' },
  'SPC-AST-050': { id: 'SPC-AST-050', screen: '명세서 · AI 어시스턴트 — 작성 안내', component: '질문 입력창', display: '"단계 진행·작성 방법을 질문하세요..." + 전송', interaction: '입력·Enter', precondition: '입력 비어 있지 않음', postcondition: '0.5초 후 응답' },
  'SPC-EDT-060': { id: 'SPC-EDT-060', screen: '명세서 · 에디터', component: '편집 툴바 (영역)', display: '한 줄 · 편집 도구만(화면 이동은 내비게이션 행). 좌: 실행 취소·다시 실행 ｜ ∑ 수식 ｜ 찾기 · 힌트 "단락을 클릭하면 수식을 삽입할 수 있습니다"(미편집 시, xl 이상) · 우: 미리보기·DOCX·PDF', interaction: '↓ 액션별', precondition: '에디터 진입', postcondition: '—' },
  'SPC-EDT-061': { id: 'SPC-EDT-061', screen: '명세서 · 에디터', component: '실행 취소 / 다시 실행', display: '두 버튼(Ctrl+Z / Ctrl+Y·Ctrl+Shift+Z)', interaction: '클릭 / 단축키(입력창 포커스 중엔 네이티브 우선)', precondition: '각 스택에 항목 존재(최대 20단계)', postcondition: '단락 상태 스냅샷 복원 · 저장은 다음 편집 시' },
  'SPC-EDT-066': { id: 'SPC-EDT-066', screen: '명세서 · 에디터', component: '표 삽입', display: '표 삽입 모달 — 행 수(1~10) · 열 3 고정', interaction: '클릭 → 행 수 → 삽입', precondition: '편집 중 단락 필요', postcondition: '마크다운 표 삽입 (API SpecificationBlock.type=table)' },
  'SPC-EDT-062': { id: 'SPC-EDT-062', screen: '명세서 · 에디터', component: '∑ 수식', display: '버튼 → 「수식 입력 (TeX / LaTeX)」 모달: 인라인 $…$/블록 $$…$$ 모드 · TeX 입력 · 실시간 미리보기(오류 시 ⚠) · 자주 쓰는 TeX 15종 · 취소/삽입', interaction: '편집 중 단락 필요(없으면 비활성)', precondition: '편집 중 단락 있음 · 수식 오류 없음', postcondition: '현재 단락 끝에 수식 추가(실행 취소 가능 · 자동 저장) · 읽기 모드에서 KaTeX 렌더' },
  'SPC-EDT-063': { id: 'SPC-EDT-063', screen: '명세서 · 에디터', component: '찾기/바꾸기', display: '토글 시 바 노출: 찾기 · N건 · 바꿀 내용 · 전체 바꾸기 · 문서 통계 N단락 · N자(공백 제외) · ✕', interaction: '입력 · 전체 바꾸기 클릭', precondition: '전체 바꾸기: 찾는 문자열 1건 이상', postcondition: '전 섹션 전 단락 일괄 치환(실행 취소 가능 · 자동 저장). ⚠ 툴팁의 Ctrl+F 단축키는 미구현' },
  'SPC-EDT-064': { id: 'SPC-EDT-064', screen: '명세서 · 에디터', component: '미리보기', display: '「명세서 미리보기」 모달 — 내용 있는 섹션만 【섹션명】 순서대로 + 【도면】(채택 도면 2열, 【도 N】 도면명) · 전체화면 토글 · 하단 닫기/DOCX 다운로드/PDF 내보내기', interaction: '클릭', precondition: '—', postcondition: '모달 표시 · 내보내기 진행 중 버튼 비활성 · 팝업 차단 시 안내 문구' },
  'SPC-EDT-065': { id: 'SPC-EDT-065', screen: '명세서 · 에디터', component: 'DOCX / PDF', display: '두 버튼(툴팁 "…내보내기 (도면 포함)")', interaction: '클릭', precondition: '—', postcondition: 'DOCX 즉시 다운로드 / PDF 인쇄용 새 창(파일명=작업 이름). 도면 이미지 포함' },
  'SPC-EDT-070': { id: 'SPC-EDT-070', screen: '명세서 · 에디터', component: '내비게이션 행 (영역)', display: '좌측 고정 ← 작성 단계로(아웃라인) ｜ 섹션 탭 11개(가로 스크롤) — 위저드 스텝바와 같은 행', interaction: '↓ 액션별', precondition: '에디터 진입', postcondition: '—' },
  'SPC-EDT-071': { id: 'SPC-EDT-071', screen: '명세서 · 에디터', component: '← 작성 단계로', display: '툴팁 "위저드(작성 단계)로 돌아갑니다 — 편집 내용은 저장됩니다"', interaction: '클릭', precondition: '—', postcondition: '위저드(8단계 화면)로 전환 · 편집 내용은 유지(재진입 시 복원)' },
  'SPC-EDT-072': { id: 'SPC-EDT-072', screen: '명세서 · 에디터', component: '섹션 탭', display: '명칭 · 기술분야 · 배경기술 · 해결과제 · 해결수단 · 효과 · 도면설명 · 부호 · 구체적 내용 · 청구범위 · 요약 · 활성 탭 brand 밑줄(본문 스크롤에 따라 자동 갱신)', interaction: '클릭', precondition: '—', postcondition: '해당 섹션 제목으로 부드럽게 스크롤' },
  'SPC-EDT-080': { id: 'SPC-EDT-080', screen: '명세서 · 에디터', component: '본문 · 섹션/단락 (영역)', display: '섹션 제목(전체 명칭) 아래 단락 카드 목록. 카드 상태: 편집 중(파란 테두리) / 체크됨(파란 배경) / 빈 단락(점선). 읽기 모드는 마크다운 표·TeX 수식·구성요소 하이라이트 렌더', interaction: '↓ 액션별', precondition: '에디터 진입', postcondition: '—' },
  'SPC-EDT-081': { id: 'SPC-EDT-081', screen: '명세서 · 에디터', component: '단락 체크(AI 대상 선택)', display: '카드 좌상단 체크박스(20px) · 툴팁 "여러 단락을 한번에 AI 수정하려면 체크하세요"', interaction: '토글', precondition: '—', postcondition: '우측 패널 「선택 단락」에 반영(1개=읽기 전용 미리보기, 여러 개=목록) · 체크 시 편집 모드 종료' },
  'SPC-EDT-082': { id: 'SPC-EDT-082', screen: '명세서 · 에디터', component: '단락 편집', display: '카드 클릭 → textarea(자동 높이). 구성요소 이름이 포함된 단락엔 안내 "구성요소 이름은 여기서 고쳐도 이 단락에만 반영됩니다. 명세서 전체에서 바꾸려면 편집을 끝낸 뒤 점선 밑줄 이름을 클릭하세요."', interaction: '클릭·입력 · 바깥 클릭/체크로 종료', precondition: '편집 중 아닌 카드', postcondition: '입력마다 실행 취소 스냅샷 + 0.5초 지연 자동 저장(editorBlocks) · 해당 단락이 AI 대상 1개로 선택됨' },
  'SPC-EDT-083': { id: 'SPC-EDT-083', screen: '명세서 · 에디터', component: '단락 이동 ▲▼', display: '카드 호버 시 노출', interaction: '클릭', precondition: '섹션 단락 2개 이상 · 첫/마지막은 해당 방향 비활성', postcondition: '순서 교환(실행 취소 가능 · 자동 저장)' },
  'SPC-EDT-084': { id: 'SPC-EDT-084', screen: '명세서 · 에디터', component: '단락 삭제 ✕', display: '호버 시 노출 · 확인 다이얼로그 「단락 삭제」: "앞 40자…" 단락을 삭제할까요? (실행 취소로 되돌릴 수 있습니다) / 빈 단락은 빈 단락을 삭제할까요? · 삭제/취소', interaction: '클릭 → 확인', precondition: '섹션 단락 2개 이상', postcondition: '단락 제거 · 선택 해제 · 실행 취소 가능' },
  'SPC-EDT-085': { id: 'SPC-EDT-085', screen: '명세서 · 에디터', component: '+ 단락 추가', display: '섹션 끝 점선 버튼', interaction: '클릭', precondition: '청구범위 이외 섹션', postcondition: '빈 단락 추가 후 즉시 편집 모드' },
  'SPC-EDT-086': { id: 'SPC-EDT-086', screen: '명세서 · 에디터', component: '구성요소 하이라이트 → 이름 전체 변경', display: '읽기 모드에서 구성요소 명칭(+부호 (100))을 mark로 표시, 점선 밑줄=클릭 가능, 툴팁 구성요소 · 부호 · 정의 — 클릭: 이름 변경. 클릭 시 모달 「구성요소 이름 전체 변경」: 설명 "기존" → 본문·청구범위·부호의 설명과 작성 단계(구성요소·청구항·중간명세서)의 모든 언급이 한 번에 바뀝니다. 부호는 유지됩니다. · 입력 · 취소/전체 변경', interaction: '하이라이트 클릭 → 새 이름 입력 → 전체 변경(Enter)', precondition: '새 이름이 비어 있지 않고 기존과 다름', postcondition: '단일 규칙: 에디터 전 섹션 + 위저드(구성요소 원천·발명 설명·명칭·요약·청구항·중간명세서) 일괄 치환, 부호 보존, 긴 이름 우선 매칭 · 토스트 ’A’ → ’B’ — 본문 N곳도 함께 바꿨습니다 · 실행 취소 가능' },
  'SPC-EDT-090': { id: 'SPC-EDT-090', screen: '명세서 · 에디터', component: '청구범위 편집기 (영역)', display: '항 카드 목록: 청구항 N + 배지 독립항(파랑) / 제M항 종속(호박) / 제M항 종속 ⚠ 번호 확인(빨강, 자기·후행 항 인용) · 종속항 들여쓰기 · 안내 "번호는 위치에 따라 자동 부여되며, 순서 변경·삭제 시 본문의 "제N항" 인용도 함께 갱신됩니다. 항을 클릭하면 편집할 수 있습니다." · 항 본문은 구성요소 하이라이트(클릭=이름 변경) · 항 체크박스(AI 수정 대상 — 단락과 동일 규칙, 선택 시 명령이 그 항에 직접 제안)', interaction: '↓ 액션별', precondition: '에디터 진입', postcondition: '—' },
  'SPC-EDT-091': { id: 'SPC-EDT-091', screen: '명세서 · 에디터', component: '항 편집', display: '항 클릭(툴팁 "클릭하여 편집") → textarea, 포커스 아웃으로 종료', interaction: '클릭·입력', precondition: '—', postcondition: '자동 저장 · 실행 취소 가능' },
  'SPC-EDT-092': { id: 'SPC-EDT-092', screen: '명세서 · 에디터', component: '항 이동 ▲▼', display: '버튼', interaction: '클릭', precondition: '첫/마지막 비활성', postcondition: '두 항 번호 교환에 맞춰 제N항 인용 자동 갱신' },
  'SPC-EDT-093': { id: 'SPC-EDT-093', screen: '명세서 · 에디터', component: '항 삭제 ✕', display: '확인 「청구항 N 삭제」: 종속항 없음 → 청구항 N을 삭제할까요? 뒤 항의 번호와 인용이 자동으로 당겨집니다. · 종속항 있음 → …인용하는 종속항 K개(청구항 A, …)가 있습니다. 함께 삭제할까요? ’이 항만 삭제’를 누르면 종속항은 남고 인용 번호가 ⚠로 표시됩니다. (함께 삭제 / 이 항만 삭제)', interaction: '클릭 → 확인', precondition: '—', postcondition: '항 제거 · 뒤 항 번호 당김 · 인용 재작성(잔존 종속항은 ⚠ 번호 확인)' },
  'SPC-EDT-094': { id: 'SPC-EDT-094', screen: '명세서 · 에디터', component: '+ 독립항 추가 / + 종속항 추가', display: '두 버튼', interaction: '클릭', precondition: '—', postcondition: '템플릿 항 추가(새 독립 청구항 내용을 입력하세요. / 제1항에 있어서, ...인, 장치.)' },
  'SPC-EDT-100': { id: 'SPC-EDT-100', screen: '명세서 · 에디터', component: '도면의 간단한 설명 · 도면 카드', display: '채택 도면 2열 그리드: 이미지 · 도 N + 라벨 배지(제안기술/종래기술/배경/효과/기타) · 도면명 · 도면 편집기 ↗', interaction: '도면 편집기 클릭', precondition: '채택 도면 1개 이상', postcondition: '새 탭에서 도면 편집기(범위 조정·CAD 변환)' },
  'SPC-EDT-101': { id: 'SPC-EDT-101', screen: '명세서 · 에디터', component: '부호의 설명 · 요약 (자동 조립)', display: '부호의 설명: 부호 있는 구성요소를 100: 명칭 줄로 조립 · 요약: 확정 요약 + 【대표도】 도 N(대표 도면 지정 시)', interaction: '일반 단락과 동일 편집', precondition: '에디터 첫 진입 시 조립(이후 저장본 유지)', postcondition: 'client 조립 — API InventionSpecification에 대응 필드 없음(사용자 결정: 유지)' },
  'SPC-EDT-010': { id: 'SPC-EDT-010', screen: '명세서 · 에디터', component: 'AI 어시스턴트 패널 (영역)', display: '우측 360px. 헤더 AI 어시스턴트 · 본문 수정 → 「선택 단락」 정보 영역 → 「대화 · 본문 수정」 대화 영역 → 입력창. 두 영역은 회색 제목 바로 구분', interaction: '단락 체크 후 명령 입력', precondition: '에디터 진입', postcondition: '의도 라우팅 → 의도별 응답' },
  'SPC-EDT-011': { id: 'SPC-EDT-011', screen: '명세서 · 에디터', component: '선택 단락 (정보 영역)', display: '제목 바 선택 단락 · N개 선택 / 미선택 · 전체 문서 대상. 1개: 선택 중 · 섹션 N + 읽기 전용 본문 + "아래 입력창에 이 단락에 대한 수정 명령을 입력하세요. 본문을 직접 고치려면 중앙의 단락을 클릭합니다." · 여러 개: 편집 명령 대상 · N개 목록 · 0개: "중앙에서 단락을 선택하면 여기에 표시됩니다. 선택 없이 명령하면 전체 문서를 대상으로 합니다." · 선택 해제', interaction: '선택 해제 클릭', precondition: '—', postcondition: '패널에서 본문을 직접 편집하지 않음(읽기 전용)' },
  'SPC-EDT-030': { id: 'SPC-EDT-030', screen: '명세서 · 에디터', component: 'AI 응답 메시지(의도 배지)', display: '배지: 답변 · 방향 확인 · 플랜 · 미지원 · 본문 수정 · 청구항 수정 · 도면 설명 수정 · 용어 교체 + 본문 · 전송 직후 「요청 분석 중...」 단계 트리(의도별 3~4단계, ✓ 진행)', interaction: '정독', precondition: '명령 전송됨', postcondition: '라우팅된 의도로 렌더 · 히스토리 축적' },
  'SPC-EDT-031': { id: 'SPC-EDT-031', screen: '명세서 · 에디터', component: '수정 제안 카드', display: '액션 배지(재작성/치환/삽입/삭제) · 대상 ’섹션’ N번째 블록 · ↗ 확대(전체 diff 모달) · 요약 · Before(빨강 diff)/After(초록 diff) · 보강 지시 입력 "대신 이렇게 해줘 (보강 지시)..." + 보내기 · 카드 묶음 아래 ↻ 다시 생성', interaction: '정독 · 보강 · 다시 생성', precondition: '수정 의도 + 대상 단락', postcondition: '단락 단위 제안 표시 · 보강 시 해당 제안만 재생성(토스트)' },
  'SPC-EDT-032': { id: 'SPC-EDT-032', screen: '명세서 · 에디터', component: '✓ 적용 / ✕ 취소', display: '두 버튼 → ✓ 적용됨 / ✕ 취소됨', interaction: '클릭', precondition: '제안 대기 중', postcondition: '적용=단락에 반영(치환/재작성=교체, 삽입=다음 위치, 삭제=제거 · 실행 취소 가능 · 자동 저장) · 취소=제안만 닫음' },
  'SPC-EDT-033': { id: 'SPC-EDT-033', screen: '명세서 · 에디터', component: '방향 선택지(clarify)', display: '"어떤 방향으로 진행할까요?" + 칩(예: 더 간결하게 / 특허 문체로 / 구체적 수치 추가)', interaction: '칩 클릭', precondition: '지시가 짧거나 모호 · 선택 없이 수정 지시', postcondition: '[선택지] 선택됨 표시 후 해당 방향 제안 생성' },
  'SPC-EDT-034': { id: 'SPC-EDT-034', screen: '명세서 · 에디터', component: '용어(표현) 교체 제안', display: '"문서 전체에서 N건의 용어(표현) 교체를 제안합니다." · 행: A → B · 반영 / 무시 → ✓ 적용됨 / ✕ 취소됨', interaction: '반영/무시 클릭', precondition: '"A"를 "B"로 바꿔 지시 또는 표기 변형 감지', postcondition: '반영=전 섹션 일괄 치환(토스트 용어가 교체되었습니다 · 실행 취소 가능)' },
  'SPC-EDT-040': { id: 'SPC-EDT-040', screen: '명세서 · 에디터', component: '플랜 진행', display: '플랜 · n / N 단계 · 상태(진행 중/중단됨/완료) · 스텝 목록 · ▶ n단계 진행 / ■ 중단', interaction: '진행/중단', precondition: '다단계 지시 · 청구항 언급 시 「독립항 검토·수정 → 종속항 검토·수정」 2단계 고정', postcondition: '스텝별 제안 생성 · 진행 중 입력창 잠금' },
  'SPC-EDT-041': { id: 'SPC-EDT-041', screen: '명세서 · 에디터', component: '미지원 안내(terminate)', display: '배지 미지원 + "요청하신 작업은 이번 버전(M2)에서 지원하지 않습니다. 외부 정보 검색(인터넷·특허·논문)과 도면 이미지 생성은 별도 기능에서…"', interaction: '정독', precondition: '외부 검색·도면 생성 요청', postcondition: '대화 종료(다른 명령 가능)' },
  'SPC-EDT-050': { id: 'SPC-EDT-050', screen: '명세서 · 에디터', component: '명령 입력창', display: 'placeholder: 명령을 입력하세요... (Enter 전송) / 선택한 N개 단락에 대해 명령하세요... / 요청 분석 중... / 플랜 진행 중 — 입력 잠금 · 전송 아이콘 버튼 · 플랜 중 경고 문구', interaction: '입력·Enter 전송(Shift+Enter 개행)', precondition: '분석 중·플랜 진행 중 아님', postcondition: '의도 라우팅 실행' },
  'SPC-EDT-110': { id: 'SPC-EDT-110', screen: '명세서 · 에디터', component: '모바일 AI 어시스턴트', display: 'md 미만: 우하단 FAB(“AI 어시스턴트 열기”) → 하단 시트(72vh)', interaction: '클릭 · 오버레이/✕로 닫기', precondition: '좁은 화면', postcondition: '패널 표시/숨김' },
};
